template_path: dynamo/accountInfo.yaml
parameters:
  Environment: {{ stack_group_config.Environment }}
  TableName: omni-dw-account-info
stack_tags:
  "Application": {{ stack_group_config.Application }}
  "CreateBy": {{ stack_group_config.CreateBy }}
  "Version": {{ stack_group_config.Version }}
  "Environment": {{ stack_group_config.Environment }}
