template_path: dynamo/wd-shipment-status.yaml
parameters:
  Environment: {{ stack_group_config.Environment }}
  TableName: omni-dw-wd-shipment-status
stack_tags:
  "Application": {{ stack_group_config.Application }}
  "CreateBy": {{ stack_group_config.CreateBy }}
  "Version": {{ stack_group_config.Version }}
  "Environment": {{ stack_group_config.Environment }}
