Parameters:
  Environment: 
    Type: String
  Name: 
    Type: String
  Description: 
    Type: String

Resources:
  ApiKey:
    Type: 'AWS::ApiGateway::ApiKey'
    Properties:
      Name: !Join ['-', [!Ref Name, !Ref Environment]]
      Description: !Join ['-', [!Ref Description, !Ref Environment]]
      Enabled: 'true'
      

Outputs:
  Id:
    Value: !Ref ApiKey
  Name:
    Value: !Join ['-', [!Ref Name, !Ref Environment]]

    