template_path: ssm/parameter.yaml
parameters:
  Name: /omni-dw/{{ stack_group_config.Environment }}/sls/deployment/bucket
  Value: !stack_output {{ stack_group_config.Environment }}/s3/sls-deploy-state-bucket.yaml::Name
  Description: Sls Deployment Bucket - {{ stack_group_config.Environment }}
stack_tags:
  "Application": {{ stack_group_config.Application }}
  "CreateBy": {{ stack_group_config.CreateBy }}
  "Version": {{ stack_group_config.Version }}
  "Environment": {{ stack_group_config.Environment }}
