template_path: ssm/parameter.yaml
parameters:
  Name: /omni-dw/{{ stack_group_config.Environment }}/createShipment/wt/url
  Value: 'https://wttest.omnilogistics.com/WTKServices/AirtrakShipment.asmx'
  Description: Worldtrak create shipment URL - {{ stack_group_config.Environment }}
stack_tags:
  "Application": {{ stack_group_config.Application }}
  "CreateBy": {{ stack_group_config.CreateBy }}
  "Version": {{ stack_group_config.Version }}
  "Environment": {{ stack_group_config.Environment }}
