template_path: api-gateway/usagePlan.yaml
parameters:
  Environment: {{ stack_group_config.Environment }}
  Description: mock API usageplan for all service APIs - {{ stack_group_config.Environment }}
  UsagePlanName: "mock-api-usageplan"
stack_tags:
  "Application": {{ stack_group_config.Application }}
  "CreateBy": {{ stack_group_config.CreateBy }}
  "Version": {{ stack_group_config.Version }}
  "Environment": {{ stack_group_config.Environment }}
