template_path: ssm/parameter.yaml
parameters:
  Name: /omni-dw/{{ stack_group_config.Environment }}/starryReport/email/receiver
  Value: ['acuartas@starry.com','lspencer@starry.com','lpietraszek@starry.com','ausops@omnilogistics.com','asalaices@omnilogistics.com','kiranv@bizcloudexperts.com','kodriscoll@starry.com','mish@bizcloudexperts.com']
  Description: Starry Report Email Sender - {{ stack_group_config.Environment }}
stack_tags:
  "Application": {{ stack_group_config.Application }}
  "CreateBy": {{ stack_group_config.CreateBy }}
  "Version": {{ stack_group_config.Version }}
  "Environment": {{ stack_group_config.Environment }}
