template_path: ssm/parameter.yaml
parameters:
  Name: /omni-dw/{{ stack_group_config.Environment }}/customerEntitlementTable
  Value: "omni-dw-customer-entitlement-dev"
  Description: Customer Entitlement DynamoDB Table


  