template_path: ssm/parameter.yaml
parameters:
  Name: Dynamics-URL-{{ stack_group_config.Environment }}
  Value: "https://prod-11.westus.logic.azure.com:443/workflows/0f11583e863e4ac495314d2b54c2d2b0/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=q5CmF-VeENwomvtNApiWJbk3yJ-Uz_knY6bGoBmrM6I"
  Description: Dynamics CRM Dev Url
stack_tags:
  Project: Omni_Dynamics
  Version: 1.0