template_path: ssm/parameter.yaml
parameters:
  Name: /omni-dw/{{ stack_group_config.Environment }}/fileNumberTable
  Value: "omni-dw-customer-file-number-dev"
  Description: Customer File Number 


  