template_path: ssm/parameter.yaml
parameters:
  Name: /omni/{{ stack_group_config.Environment }}/mock/api/usagePlan/name
  Value: !stack_output {{ stack_group_config.Environment }}/api-gateway/mockUsageplan.yaml::Name
  Description: mock API UsagePlan name - {{ stack_group_config.Environment }}