template_path: ssm/parameter.yaml
parameters:
  Name: /omni-dw/{{ stack_group_config.Environment }}/shipmentDetailsTable
  Value: "omni-dw-shipment-details-dev"
  Description: Shipment Details DynamoDB Table


  