template_path: ssm/parameter.yaml
parameters:
  Name: /omni-dw/{{ stack_group_config.Environment }}/shipmentDetailsTableIndex
  Value: "HouseBillKeyIndex"
  Description: Shipment Details Table Index


  