template_path: ssm/parameter.yaml
parameters:
  Name: /omni-project44-api-services/{{ stack_group_config.Environment }}/url
  Value: "https://cloud.p-44.com/api/v4/capacityproviders/ltl/shipments/statusupdates"
  Description: Project 44 API Endpoint URL - {{ stack_group_config.Environment }}
stack_tags:
  "Application": {{ stack_group_config.Application }}
  "CreateBy": {{ stack_group_config.CreateBy }}
  "Version": {{ stack_group_config.Version }}
  "Environment": {{ stack_group_config.Environment }}
