template_path: dynamo/cargoWiseS3Trigger.yaml
parameters:
  Environment: {{ stack_group_config.Environment }}
  TableName: omni-warehouse-s3-trigger
stack_tags:
  "Application": {{ stack_group_config.Application }}
  "CreateBy": {{ stack_group_config.CreateBy }}
  "Version": {{ stack_group_config.Version }}
  "Environment": {{ stack_group_config.Environment }}
