template_path: dynamo/netsuiteErrorTable.yaml
parameters:
  Environment: {{ stack_group_config.Environment }}
  TableName: omni-dw-netsuit-ar-error-response
stack_tags:
  "Application": {{ stack_group_config.Application }}
  "CreateBy": {{ stack_group_config.CreateBy }}
  "Version": {{ stack_group_config.Version }}
  "Environment": {{ stack_group_config.Environment }}
