template_path: ssm/parameter.yaml
parameters:
  Name: /omni-dw/{{ stack_group_config.Environment }}/entitlement/fileNumber/index
  Value: "FileNumberindex"
  Description: Customer Entitlement Table File Number Index - {{ stack_group_config.Environment }}
