template_path: ssm/parameter.yaml
parameters:
  Name: /omni-dw/{{ stack_group_config.Environment }}/entitlement/houseBillNumber/index
  Value: "HouseBillNumberindex"
  Description: Customer Entitlement Table House Bill Number Index - {{ stack_group_config.Environment }}
