template_path: ssm/parameter.yaml
parameters:
  Name: /omni-dw/{{ stack_group_config.Environment }}/netsuitAR/authConfig/tokenSecretCW
  Value: "69de4c46895ee2ad386fdd78a7b7df3d7dae8642df6bd8edb5b9eadb00d89403"
  Description: netsuitAR tokenSecretCW - {{ stack_group_config.Environment }}
stack_tags:
  "Application": {{ stack_group_config.Application }}
  "CreateBy": {{ stack_group_config.CreateBy }}
  "Version": {{ stack_group_config.Version }}
  "Environment": {{ stack_group_config.Environment }}
