template_path: ssm/parameter.yaml
parameters:
  Name: /omni-dw/hydraFacialReport/{{ stack_group_config.Environment }}/smtp/user
  Value: "AKIAXLP624BLJQ5JICVQ"
  Description: Hydrafacial smtp user - {{ stack_group_config.Environment }}
stack_tags:
  "Application": {{ stack_group_config.Application }}
  "CreateBy": {{ stack_group_config.CreateBy }}
  "Version": {{ stack_group_config.Version }}
  "Environment": {{ stack_group_config.Environment }}
