template_path: ssm/parameter.yaml
parameters:
  Name: /omni-dw/hydraFacialReport/{{ stack_group_config.Environment }}/dynamoDb/table/name
  Value: "omni-prod-hydrafacial-delivered-shipment"
  Description: Hydrafacial smtp dynamodb table - {{ stack_group_config.Environment }}
stack_tags:
  "Application": {{ stack_group_config.Application }}
  "CreateBy": {{ stack_group_config.CreateBy }}
  "Version": {{ stack_group_config.Version }}
  "Environment": {{ stack_group_config.Environment }}