AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Environment: 
    Type: String
  TableName: 
    Type: String
    
Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - 
        AttributeName: "id"
        AttributeType: "S"
      - 
        AttributeName: "file_nbr"
        AttributeType: "S"
      KeySchema:
      - 
        AttributeName: "id"
        KeyType: "HASH"
      - 
        AttributeName: "file_nbr"
        KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "0"
        WriteCapacityUnits: "0"
      TableName: !Join ['-', [!Ref TableName, !Ref Environment]]
      SSESpecification:
        SSEEnabled: true 

Outputs:
  Name:
    Value: !Ref Table
  Arn:
    Value: !GetAtt Table.Arn
