template_path: ssm/parameter.yaml
parameters:
  Name: /omni-dw/{{ stack_group_config.Environment }}/api/key/mock-user-1
  Value: !stack_output {{ stack_group_config.Environment }}/api-gateway/mockUser1-key.yaml::Name
  Description: api key for mock user 1 - {{ stack_group_config.Environment }}
stack_tags:
  "Application": {{ stack_group_config.Application }}
  "CreateBy": {{ stack_group_config.CreateBy }}
  "Version": {{ stack_group_config.Version }}
  "Environment": {{ stack_group_config.Environment }}
