template_path: dynamo/project44-payload.yaml
parameters:
  Environment: {{ stack_group_config.Environment }}
  TableName: omni-dw-project-44-payload
stack_tags:
  "Application": {{ stack_group_config.Application }}
  "CreateBy": {{ stack_group_config.CreateBy }}
  "Version": {{ stack_group_config.Version }}
  "Environment": {{ stack_group_config.Environment }}
