template_path: ssm/parameter.yaml
parameters:
  Name: /omni-crm/{{ stack_group_config.Environment }}/globalCustomers/s3/key
  Value: "Data/global_customers.txt"
  Description: Omni crm global customers S3 Key - {{ stack_group_config.Environment }}
stack_tags:
  "Application": {{ stack_group_config.Application }}
  "CreateBy": {{ stack_group_config.CreateBy }}
  "Version": {{ stack_group_config.Version }}
  "Environment": {{ stack_group_config.Environment }}
