template_path: ssm/parameter.yaml
parameters:
  Name: /omni-dw/{{ stack_group_config.Environment }}/customerEntitlement/table
  Value: !stack_output {{ stack_group_config.Environment }}/dynamo/entitlement.yaml::Name
  Description: Customer Entitlement DynamoDB Table Name - {{ stack_group_config.Environment }}
stack_tags:
  "Application": {{ stack_group_config.Application }}
  "CreateBy": {{ stack_group_config.CreateBy }}
  "Version": {{ stack_group_config.Version }}
  "Environment": {{ stack_group_config.Environment }}
