template_path: ssm/parameter.yaml
parameters:
  Name: /omni-dw-fourkites/{{ stack_group_config.Environment }}/auth/password
  Value: "APIpa$$word01"
  Description: Omni fourkites auth password - {{ stack_group_config.Environment }}
stack_tags:
  "Application": {{ stack_group_config.Application }}
  "CreateBy": {{ stack_group_config.CreateBy }}
  "Version": {{ stack_group_config.Version }}
  "Environment": {{ stack_group_config.Environment }}
