template_path: ssm/parameter.yaml
parameters:
  Name: /omni-dw-fourkites/{{ stack_group_config.Environment }}/url
  Value: "https://tracking-api-staging.fourkites.com/api/v1/tracking/dispatcher_updates"
  Description: Omni fourkites URL - {{ stack_group_config.Environment }}
stack_tags:
  "Application": {{ stack_group_config.Application }}
  "CreateBy": {{ stack_group_config.CreateBy }}
  "Version": {{ stack_group_config.Version }}
  "Environment": {{ stack_group_config.Environment }}
