template_path: ssm/parameter.yaml
parameters:
  Name: /omni-project44-api-services/{{ stack_group_config.Environment }}/auth/password
  Value: "Project44!"
  Description: Project 44 API Endpoint password - {{ stack_group_config.Environment }}
stack_tags:
  "Application": {{ stack_group_config.Application }}
  "CreateBy": {{ stack_group_config.CreateBy }}
  "Version": {{ stack_group_config.Version }}
  "Environment": {{ stack_group_config.Environment }}
