template_path: ssm/parameter.yaml
parameters:
  Name: /omni-dw/{{ stack_group_config.Environment }}/netsuitAR/errorEmail/to
  Value: "kazi.ali@bizcloudexperts.com,kiranv@bizcloudexperts.com,swillingham@omnilogistics.com,psotelo@omnilogistics.com,bcastilleja@omnilogistics.com"
  Description: netsuite errorEmail to - {{ stack_group_config.Environment }}
stack_tags:
  "Application": {{ stack_group_config.Application }}
  "CreateBy": {{ stack_group_config.CreateBy }}
  "Version": {{ stack_group_config.Version }}
  "Environment": {{ stack_group_config.Environment }}
