template_path: ssm/parameter.yaml
parameters:
  Name: /omni-dw/{{ stack_group_config.Environment }}/netsuitAR/authConfig/tokenSecret
  Value: "83bba47e64990cdb3133472e01bff2a0b9150fb303cecdf4f9ed7f754424ddf"
  Description: netsuite authconfig tokenSecret - {{ stack_group_config.Environment }}
stack_tags:
  "Application": {{ stack_group_config.Application }}
  "CreateBy": {{ stack_group_config.CreateBy }}
  "Version": {{ stack_group_config.Version }}
  "Environment": {{ stack_group_config.Environment }}
