template_path: ssm/parameter.yaml
parameters:
  Name: /omni-crm/{{ stack_group_config.Environment }}/customers/url
  Value: "https://prod-59.westus.logic.azure.com:443/workflows/85d2d90796704fd28ed712e4d68faffd/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=ux_hHmC5-KjI5Vyz1u1OTgFyPEqmVxMtL3_aCcnzvNQ"
  Description: Omni crm customers table URL - {{ stack_group_config.Environment }}
stack_tags:
  "Application": {{ stack_group_config.Application }}
  "CreateBy": {{ stack_group_config.CreateBy }}
  "Version": {{ stack_group_config.Version }}
  "Environment": {{ stack_group_config.Environment }}
