template_path: redshift-cluster/redshift.yaml
parameters:
  ClusterIdentifier: omni-dw-prod
  Environment: {{ stack_group_config.Environment }}
  ClusterSubnetGroupName: omni-redshift
  ClusterType: single-node
  DBName: dev
  MasterUsername: bceuser1
  MasterUserPassword: BizCloudExp1
  NodeType: dc2.large

stack_tags:
  "Application": {{ stack_group_config.Application }}
  "CreateBy": {{ stack_group_config.CreateBy }}
  "Version": {{ stack_group_config.Version }}
  "Environment": {{ stack_group_config.Environment }}
